config/routes.rb
Rails.application.routes.draw do
  resources :stocks
  resources :fuel_types
  resources :users

  get "/signup", to: "users#new"
  root "sessions#new"
  post "/login", to:"sessions#create"
  delete "/logout", to: "sessions#destroy"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/fuel_type.rb
class FuelType < ApplicationRecord
  belongs_to :user
end

app/models/stock.rb
class Stock < ApplicationRecord
  belongs_to :User
end

app/models/user.rb
class User < ApplicationRecord
    
    has_many :fuel_types

    before_save {self.email=email.downcase}
    validates :username,
     presence: true,
     uniqueness:{case_sensitive: false}, 
     length: {minimum: 3, maximum: 25}

    VALID_EMAIL_REGEX= /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i

    validates :email, presence: true,length: {maximum:150},
    uniqueness:{case_sensitive: false}, 
    format: { with: VALID_EMAIL_REGEX }
    

    has_secure_password

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

    protect_from_forgery with: :exception

    helper_method :current_user, :logged_in?, :require_user

    def current_user

       @current_user ||= User.find(session[:user_id]) if session[:user_id]

    end

    def logged_in?

        !!current_user

    end

    def require_user
        if !logged_in?
            #flash[:danger] = "You Must be Logged in"
            redirect_to root_path
        end

    end
end

app/controllers/fuel_types_controller.rb
class FuelTypesController < ApplicationController
  before_action :set_fuel_type, only: [:show, :edit, :update, :destroy]

  # GET /fuel_types
  # GET /fuel_types.json
  def index
    if not logged_in? 
      redirect_to root_path
      
    else
       
      @fuel_types = FuelType.paginate(page: params[:page], per_page: 6)
    end
  end

  # GET /fuel_types/1
  # GET /fuel_types/1.json
  def show
  end

  # GET /fuel_types/new
  def new
    @fuel_type = FuelType.new
  end

  # GET /fuel_types/1/edit
  def edit
  end

  # POST /fuel_types
  # POST /fuel_types.json
  def create
    @fuel_type = FuelType.new(fuel_type_params)

    respond_to do |format|
      if @fuel_type.save
        format.html { redirect_to @fuel_type, notice: 'Fuel type was successfully created.' }
        format.json { render :show, status: :created, location: @fuel_type }
      else
        format.html { render :new }
        format.json { render json: @fuel_type.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /fuel_types/1
  # PATCH/PUT /fuel_types/1.json
  def update
    respond_to do |format|
      if @fuel_type.update(fuel_type_params)
        format.html { redirect_to @fuel_type, notice: 'Fuel type was successfully updated.' }
        format.json { render :show, status: :ok, location: @fuel_type }
      else
        format.html { render :edit }
        format.json { render json: @fuel_type.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /fuel_types/1
  # DELETE /fuel_types/1.json
  def destroy
    @fuel_type.destroy
    respond_to do |format|
      format.html { redirect_to fuel_types_url, notice: 'Fuel type was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_fuel_type
      @fuel_type = FuelType.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def fuel_type_params
      params.require(:fuel_type).permit(:fuelname, :price, :user_id)
    end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
    
    def new
        redirect_to fuel_types_path if logged_in? 
    end

    def create
        user = User.find_by(email: params[:session][:email].downcase)
        if user && user.authenticate(params[:session][:password])
            session[:user_id]= user.id
            #flah[:success]="Wecome #{user.username}"
            redirect_to user_path(user)

        else
            #flah.now[:danger]="User Name or password Incorrect"
            redirect_to root_path

        end
    end

    def destroy
        session[:user_id]= nil
        #flah[:success]="You have successfully been loged out"
        redirect_to root_path

    end

end

app/controllers/stocks_controller.rb
class StocksController < ApplicationController
  before_action :set_stock, only: [:show, :edit, :update, :destroy]

  # GET /stocks
  # GET /stocks.json
  def index
    @stocks = Stock.all
  end

  # GET /stocks/1
  # GET /stocks/1.json
  def show
  end

  # GET /stocks/new
  def new
    @stock = Stock.new
  end

  # GET /stocks/1/edit
  def edit
  end

  # POST /stocks
  # POST /stocks.json
  def create
    @stock = Stock.new(stock_params)

    respond_to do |format|
      if @stock.save
        format.html { redirect_to @stock, notice: 'Stock was successfully created.' }
        format.json { render :show, status: :created, location: @stock }
      else
        format.html { render :new }
        format.json { render json: @stock.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /stocks/1
  # PATCH/PUT /stocks/1.json
  def update
    respond_to do |format|
      if @stock.update(stock_params)
        format.html { redirect_to @stock, notice: 'Stock was successfully updated.' }
        format.json { render :show, status: :ok, location: @stock }
      else
        format.html { render :edit }
        format.json { render json: @stock.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /stocks/1
  # DELETE /stocks/1.json
  def destroy
    @stock.destroy
    respond_to do |format|
      format.html { redirect_to stocks_url, notice: 'Stock was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_stock
      @stock = Stock.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def stock_params
      params.require(:stock).permit(:fueltype, :liters, :totalliters, :User_id)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  # GET /users
  # GET /users.json
  def index
    @users = User.all
  end

  # GET /users/1
  # GET /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    private
    def user_params
      params.require(:user).permit(:username, :email,:password)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
    def gravatar_for(user,options={size:80})
        gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
        size = options[:size]
        gravatar_url ="http://secure.gravatar.com/avatar/#{gravatar_id}?s=#{size}"
        image_tag(gravatar_url,alt: user.username, class:'rounded')
    end
end

app/helpers/fuel_types_helper.rb
module FuelTypesHelper
end

app/helpers/stocks_helper.rb
module StocksHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/fuel_types/_form.html.erb
<div class="container">
    <%= form_with(model: fuel_type, local: true) do |form| %>
    <% if fuel_type.errors.any? %>
      <div id="error_explanation">
        <h2><%= pluralize(fuel_type.errors.count, "error") %> prohibited this fuel_type from being saved:</h2>
  
        <ul>
        <% fuel_type.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
        </ul>
      </div>
    <% end %>
      <div class="col-md-8 offset-md-2">

          <div class="card" style="padding: 5vh; background-color:#0000008a;">
  
              <div class="form-group row">
                  <%= form.label :fuelname, class:"col-sm-2 col-form-label" %>
                  <div class="col-sm-10">
                      <%= form.text_field :fuelname,class:"form-control" %>
                  </div>
                </div>
              
                <div class="form-group row">
                  <%= form.label :price, class:"col-sm-2 col-form-label" %>
                  <div class="col-sm-10">
                      <%= form.number_field :price, class:"form-control" %>
                  </div>
                </div>
              
                <div class="actions">
                  <%= form.submit 'Add',class:'btn btn-secondary btn-block' %>
                </div>
                </div>
      </div>
  <% end %>
  
</div>

app/views/fuel_types/edit.html.erb
<h1>Editing Fuel Type</h1>

<%= render 'form', fuel_type: @fuel_type %>

<%= link_to 'Show', @fuel_type %> |
<%= link_to 'Back', fuel_types_path %>

app/views/fuel_types/index.html.erb
<div class="row">
  <div class="container">
      <p id="notice"><%= notice %></p>

      

      <h1 align = 'center'>Fuel Types</h1>
      <div style="text-align: center; margin-top:5vh; margin-bottom:5vh;">
          <%= link_to 'New Fuel Type', new_fuel_type_path, class:'btn btn-secondary btn-lg text-center' %>
      

      </div>
      
      <table class="table table-dark table-hover">
        <thead>
          <tr>
            <th>Fuelname</th>
            <th>Price</th>
            <th>Added by</th>
            <th colspan="3"></th>
          </tr>
        </thead>
      
        <tbody>
          <% @fuel_types.each do |fuel_type| %>
            <tr>
              <td><%= fuel_type.fuelname %></td>
              <td><%= fuel_type.price %></td>
              <td><%= fuel_type.user.username %></td>
              <td><%= link_to 'Show', fuel_type, class:'btn btn-sm btn-success'%></td>
              <td><%= link_to 'Edit', edit_fuel_type_path(fuel_type),class:'btn btn-sm btn-primary' %></td>
              <td><%= link_to 'Destroy', fuel_type, method: :delete, data: { confirm: 'Are you sure?' },class:'btn btn-sm btn-danger' %></td>
            </tr>
          <% end %>
        </tbody>
      </table>
      
      <br>
      
      
      
  </div>
</div>

app/views/fuel_types/new.html.erb
<div class="container">
        <h1 align=center style="margin-bottom: 10vh; margin-top:5vh;">New Fuel Type</h1>

        <%= render 'form', fuel_type: @fuel_type %>
        <div class="col-md-4 offset-md-4" style="margin-top: 5vh;">
                <%= link_to 'Fuel Types', fuel_types_path, class:'btn btn-secondary btn-block' %>
        </div>
        
</div>

app/views/fuel_types/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Fuelname:</strong>
  <%= @fuel_type.fuelname %>
</p>

<p>
  <strong>Price:</strong>
  <%= @fuel_type.price %>
</p>

<p>
  <strong>User:</strong>
  <%= @fuel_type.user %>
</p>

<%= link_to 'Edit', edit_fuel_type_path(@fuel_type) %> |
<%= link_to 'Back', fuel_types_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>FuelChit</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>

      <%= render  "resource/navbar" %>
    <%= yield %>
  </body>
</html>

app/views/resource/_errors.html.erb
<% if obj.errors.any? %>
          <div id="error_explanation">
            <div class="row">
              <div class="col-xs-8 col-xs-offset-2">
                <div class="panel panel-danger">
                  <div class="panel-heading">
                      <h2><%= pluralize(obj.errors.count, "error") %> prohibited this article from being saved:</h2>

                  </div>

                  <div class="panel-body"> 
                      
                      <ul>
                          <% obj.errors.full_messages.each do |message| %>
                            <li><%= message %></li>
                          <% end %>
                          </ul>
                </div>

                </div>

              </div>

            </div>
            
      
            
          </div>
<% end %>
      
      

app/views/resource/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-dark ">
        <%= link_to  "Fuel Chit", root_path, class:'navbar-brand' %>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
      
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
          <ul class=" navbar-nav ml-auto">
            <li class="nav-item active">
              
            </li>
            <% if logged_in? %>
            
            
              <li class="nav-item">
                  <%= link_to  "Fuel Type", fuel_types_path,  class:'nav-link' %> 
              </li>


              <li class="nav-item dropdown">
              
                  <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                   Welcome 
                  </a>
                  <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                      <%= link_to  "View Profile", user_path(current_user),  class:'dropdown-item' %> 
                      <%= link_to  "Edit Profile", edit_user_path(current_user),  class:'dropdown-item' %> 
                    <div class="dropdown-divider"></div>
                    <%= link_to  "Logout", logout_path, method: :delete, class:'dropdown-item' %> 
                  </div>
                </li>
            <% else %>
            <li class="nav-item">
                <%= link_to  "Log In", root_path,  class:'nav-link' %> 
            </li>
            <li class="nav-item">
                <%= link_to  "sign Up", signup_path,  class:'nav-link' %> 
            </li>
          </ul>
          

          <%end%>
        </div>
      </nav>

app/views/stocks/_form.html.erb
<%= form_with(model: stock, local: true) do |form| %>
  <% if stock.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(stock.errors.count, "error") %> prohibited this stock from being saved:</h2>

      <ul>
      <% stock.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :fueltype %>
    <%= form.text_field :fueltype %>
  </div>

  <div class="field">
    <%= form.label :liters %>
    <%= form.number_field :liters %>
  </div>

  <div class="field">
    <%= form.label :totalliters %>
    <%= form.number_field :totalliters %>
  </div>

  <div class="field">
    <%= form.label :User_id %>
    <%= form.text_field :User_id %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/stocks/edit.html.erb
<h1>Editing Stock</h1>

<%= render 'form', stock: @stock %>

<%= link_to 'Show', @stock %> |
<%= link_to 'Back', stocks_path %>

app/views/stocks/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Stocks</h1>

<table>
  <thead>
    <tr>
      <th>Fueltype</th>
      <th>Liters</th>
      <th>Totalliters</th>
      <th>User</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @stocks.each do |stock| %>
      <tr>
        <td><%= stock.fueltype %></td>
        <td><%= stock.liters %></td>
        <td><%= stock.totalliters %></td>
        <td><%= stock.User %></td>
        <td><%= link_to 'Show', stock %></td>
        <td><%= link_to 'Edit', edit_stock_path(stock) %></td>
        <td><%= link_to 'Destroy', stock, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Stock', new_stock_path %>

app/views/stocks/new.html.erb
<h1>New Stock</h1>

<%= render 'form', stock: @stock %>

<%= link_to 'Back', stocks_path %>

app/views/stocks/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Fueltype:</strong>
  <%= @stock.fueltype %>
</p>

<p>
  <strong>Liters:</strong>
  <%= @stock.liters %>
</p>

<p>
  <strong>Totalliters:</strong>
  <%= @stock.totalliters %>
</p>

<p>
  <strong>User:</strong>
  <%= @stock.User %>
</p>

<%= link_to 'Edit', edit_stock_path(@stock) %> |
<%= link_to 'Back', stocks_path %>

app/views/users/_form.html.erb
<div class="row">
  <div class="col">
      <%= render  "resource/errors", obj: @user %>
    <div class="card col-md-4 offset-md-4" style="padding: 5vh; background-color:#0000008a;">

        <%= form_with(model: user, local: true) do |form| %>
    
      
        <div class="form-group">
          <%= form.label :username %>
          <%= form.text_field :username, class:'form-control',placeholder:'Enter User Name' %>
        </div>
      
        <div class="form-group">
          <%= form.label :email %>
          <%= form.email_field :email, class:'form-control', placeholder:'Enter Email' %>
        </div>

        <div class="form-group">
            <%= form.label :Password %>
            <%= form.password_field :password, class:'form-control' %>
          </div>

          <div class="form-group">
              <%= form.label :password_confirm %>
              <%= form.password_field :password_confirm, class:'form-control' %>
            </div>
      
        <div class="actions">
          <%= form.submit(@user.new_record? ? "Sign up" : "Udate Account", class:'btn btn-primary btn-lg btn-block') %>
        </div>
      <% end %>
      
    </div>


      

  </div>
</div>

app/views/users/edit.html.erb
<h1 align = center>Update User</h1>

<%= render 'form', user: @user %>


<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<div class="container">

    <p id="notice"><%= notice %></p>

    <h1 align=center>System Users</h1>
    
    <div align=center  style="margin-top:10vh; margin-bottom:5vh">
        <%= link_to 'New User', new_user_path, class:'btn btn-secondary btn-lg' %>
    
    </div>
    
    <div align='center' >
        
    
    <table class="table table-dark table-hover">
      <thead>
        <tr>
          <th>Username</th>
          <th>Email</th>
          <th colspan="3">Actions</th>
        </tr>
      </thead>
    
      <tbody>
        <% @users.each do |user| %>
          <tr>
            <td><%= user.username %></td>
            <td><%= user.email %></td>
            <td><%= link_to 'Show', user,class:'btn btn-success btn-sm' %></td>
            <td><%= link_to 'Edit', edit_user_path(user),class:'btn btn-primary btn-sm' %></td>
            <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' },class:'btn btn-danger btn-sm' %></td>
          </tr>
        <% end %>
      </tbody>
    </table>
    
    
    <br>
    
    
    
</div>

app/views/users/new.html.erb
<h1 align = center>Sign up</h1>

<div class="frm">
        <%= render 'form', user: @user %>

</div>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<h1 align=center>Welcome to <%= @user.username %>'s Page</h1>

<div class="row">
  <div class="col-md-4 offset-md-4 text-center">
    <%= gravatar_for @user, size:150 %>
  </div>
</div>

<h4 align="center">
    <%= @user.email %>
  </h4>

<h4 align="center"><%= @user.username %>'s Consumptions</h4>
  